name: CI

on:
  push:
    branches: [ "release/**", "hotfix/**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'Build and Unit Test'
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm test

  # pulling merge comitts back in dev     
  merge-in-dev:
    if: ${{ github.ref_name != 'dev' }}
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - name: merge-in-dev
      run: |
        echo gh event is ${{ github.event_name}}
        gh pr create  --title "CI: automerge dev <- ${{github.ref_name}} [skip ci]" --body "CI: Automatic PR bringing commits in ${{github.ref_name}} to dev [skip ci]" --base dev 
        gh pr merge --admin --merge
      env:
        GH_TOKEN: ${{ secrets.PAT_TOKEN_GHA_AUTH }}
