name: Node.js CICD

on:
  push:
    branches: [ "dev", "main", "release/**", "hotfix/**" ]
  pull_request:
    branches: [ "dev", "main", "release/**", "hotfix/**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm test

  # publishing to github and npm
  publish-gpr:
    if: ${{ github.ref_name == 'main' }}
    needs: [build, bump-version]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      
      # - name: Install dependencies
      #   run: npm install
  
      # - name: Build the package
      #   run: npm run build

      # - name: Publish the package
      #   run: npm publish

      # - name: Publish the dist folder
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: dist
      #     path: dist
      - run: npm ci
      - run: npm run build
      - run: npm publish
      - name: Publish the dist folder
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  publish-npm:
    if: ${{ github.ref_name == 'main' }}
    needs: [build, bump-version]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      
      # - name: Install dependencies
      #   run: npm install

      # - name: Build the package
      #   run: npm run build

      # - name: Publish the package
      #   run: npm publish

      # - name: Publish the dist folder
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: dist
      #     path: dist
      - run: npm ci
      - run: npm run build
      - run: npm publish --access public
      - name: Publish the dist folder
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  # pulling merge comitts back in dev          
  pull-request:
    if: ${{ github.ref_name != 'dev' && github.event_name == 'push' }}
    needs: [build, bump-version]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - name: pull-request
      run: |
        echo gh event is ${{ github.event_name}}
        gh pr create  --title "automerge dev <- ${{github.ref_name}}" --body "Automatic PR bringing commits in ${{github.ref_name}} to dev" --base dev 
        gh pr merge --admin --merge
      env:
        GH_TOKEN: ${{ secrets.PAT_TOKEN_GHA_AUTH }}

  # bump version only if pushing to main branch
  bump-version:
    if: ${{ github.ref_name == 'main' }}
    needs: build
    name: 'Bump Version on the current rc branch'
    runs-on: ubuntu-latest
    permissions:
        packages: write
        contents: write
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v4'
        with:  
          token: ${{ secrets.PAT_TOKEN_GHA_AUTH }}
      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
          commit-message: 'CI: bumps version to {{version}} [skip ci]'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN_GHA_AUTH }}
          GITHUB_USER: akrsmv
      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"