name: CI

on:
  pull_request:
    branches: [ "dev", "main", "release/**", "hotfix/**" ]
  push:
    branches: [ "dev", "main", "release/**", "hotfix/**" ]

jobs:
  build: 
    uses: ./.github/workflows/nodejs-build.yml
  sonar-scan:
    needs: build
    uses: ./.github/workflows/sonar-scan.yml
  bump-version:
    if: ${{ github.ref_name == 'main' && github.event_name == 'push'}}
    needs: build
    permissions:
      packages: write
      contents: write
    name: 'if main branch: Bump Version'
    uses: ./.github/workflows/bump-version.yml
  merge-in-dev-after-bump-version:
    if: ${{ github.ref_name != 'dev' && github.event_name == 'push' }}
    needs: [build,bump-version]
    permissions:
      pull-requests: write
    uses: ./.github/workflows/merge-in-dev.yml
  merge-in-dev:
    if: ${{ github.ref_name != 'dev' && github.event_name == 'push' }}
    needs: build
    permissions:
      pull-requests: write
    uses: ./.github/workflows/merge-in-dev.yml
