name: gitflow

on:
  push:
    branches:
    - "release/*"
    - "main"

needs:
  - .github/workflows/bump-version-on-merge-to-main.yml

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout source code'
      uses: 'actions/checkout@v4'
      with:  
        token: ${{ secrets.PAT_TOKEN_GHA_AUTH }}
    - id: pull-request
      name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: dev
        pr_title: "Pulling ${GITHUB_REF#refs/heads/} into dev"
        pr_body: "This is an automated Pull Request containing all changes that exist in ${GITHUB_REF#refs/heads/} that do not yet exist in dev"
        pr_label: "automated"
        github_token: ${{ secrets.PAT_TOKEN_GHA_AUTH }}
    - id: approve-pull-request
      if: ${{steps.pull-request.outputs.pr_number != ''}}
      uses: hmarr/auto-approve-action@v2
      with:
        github-token: ${{ secrets.PAT_TOKEN_GHA_AUTH }}
        pull-request-number: ${{ steps.pull-request.outputs.pr_number }}
    - name: automerge
      if: ${{steps.pull-request.outputs.pr_number != ''}}
      uses: "pascalgn/automerge-action@v0.14.3"
      env:
        GITHUB_TOKEN: "${{ secrets.PAT_TOKEN_GHA_AUTH }}"
        PULL_REQUEST: "${{ steps.pull-request.outputs.pr_number }}"
        MERGE_LABELS: ""
        MERGE_RETRIES: "0"
