name: SonarCloud Batch

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: sonarsource/sonarcloud-github-action@v4.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          organization: inctasoft
          project: simple-log-ts
          branch: ${{ github.ref }}