name: CI

on:
  workflow_call: 

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: sonarsource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args:
          # Unique keys of your project and organization. You can find them in SonarCloud > Information (bottom-left menu)
          # mandatory
          -Dsonar.projectKey=inctasoft_simple-log-ts
          -Dsonar.organization=inctasoft
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
          -Dsonar.typescript.tsconfigPaths=tsconfig.json
          -Dsonar.sources=src
          -Dsonar.tests=test
